### PR TITLE
Avoid truncated logs by using spawnSync to inherit stdio streams

### PR DESCRIPTION
**Pull request by curvedriver**
Replaced `exec` calls with `spawnSync` to ensure that huge logs will not be truncated.

`child_process.exec` uses a buffer for stdio and  stderr which causes truncated logs if `npm audit` logs thousands of security vulnerabilities.

`shell: true` is necessary to avoid ENOENT in case of npx and npm because these are CMD files with a *.cmd extension.

### CODE REVIEW

**Comment by curvedriver** [comment]
Hi @tnobody ,
I updated this PR to 1.3.1.  Do you have any plans to merge this PR?

**Comment by curvedriver** [comment]
> Hi @tnobody ,
> I updated this PR to 1.3.1. Do you have any plans to merge this PR?

@svettwer are you able to merge this PR?

**Comment by svettwer** [comment]
Hi @curvedriver :wave: 
Yes, I'll take a look at it next week when I'm on vacation. :+1:

**Comment by curvedriver** [comment]
thanks @svettwer !

**Comment by curvedriver** [comment]
@svettwer , thanks for merging!

**Comment by svettwer** [comment]
You're welcome and thx for your contribution! Your changes have been released under version 1.3.2.
Happy auditing! :tada:

**Pull request merged**
